package com.BillingApp.Model;

import com.itextpdf.text.*;
import java.util.Date;

public class PDF {
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);

    public static void addPage(Document document, String text)
            throws DocumentException {
        Paragraph continut = new Paragraph();
        addEmptyLine(continut, 1);
        continut.add(new Paragraph("Bilet electronic", catFont));
        addEmptyLine(continut, 1);
        continut.add(new Paragraph(
                "Generated by: " + System.getProperty("user.name") + ", " + new Date(), smallBold));
        addEmptyLine(continut, 3);
        continut.add(new Paragraph(text, smallBold));
        addEmptyLine(continut, 8);
        continut.add(new Paragraph(
                "Don't forget to print out your ticket!", redFont));
        document.add(continut);
    }

    public static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}